name: Fitter_Job_Update_System

on:
  workflow_dispatch:  # इससे तुम्हें 'Run workflow' बटन मिलेगा
  schedule:
    - cron: '0 0 * * *' # यह रोज़ रात 12 बजे अपने आप चलेगा

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Libraries
        run: pip install feedparser requests

      - name: Run Scraper
        run: python update_jobs.py  # यह तुम्हारी पाइथन फाइल को चलाएगा

      - name: Update Database
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add jobs.json
          git commit -m "Vancancy count updated" || exit 0
          git push
